# Generated by Django 5.2 on 2025-04-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malitra_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='text',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
