# Generated by Django 5.2 on 2025-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malitra_service', '0002_remove_chatbot_text_chatbot_answer_chatbot_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='date',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
