# Generated by Django 5.2 on 2025-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malitra_service', '0003_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
    ]
